# Generated by Django 3.1.4 on 2020-12-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_auto_20201208_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
